// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCps0rSRnkgFnwBx688UpE7VwR2r_4XV_o',
    appId: '1:925708112094:web:3c70902075b38796c2324f',
    messagingSenderId: '925708112094',
    projectId: 'labs3-firebase-dc7c6',
    authDomain: 'labs3-firebase-dc7c6.firebaseapp.com',
    storageBucket: 'labs3-firebase-dc7c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBacdizbaJFOFH-uZmxTrPdteSCGzW9mTo',
    appId: '1:925708112094:android:8429858ba1aa2652c2324f',
    messagingSenderId: '925708112094',
    projectId: 'labs3-firebase-dc7c6',
    storageBucket: 'labs3-firebase-dc7c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaNBSJBocRAfYC_ncKZizBPuH6XXtunEo',
    appId: '1:925708112094:ios:6ecae21e16cf97e3c2324f',
    messagingSenderId: '925708112094',
    projectId: 'labs3-firebase-dc7c6',
    storageBucket: 'labs3-firebase-dc7c6.firebasestorage.app',
    iosBundleId: 'com.mis.lab3.labs3',
  );
}
